# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 02:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0003_auto_20170427_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postad',
            name='user',
        ),
        migrations.DeleteModel(
            name='PostAd',
        ),
    ]
