# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 12:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0014_profile_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='emails',
        ),
    ]
