# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0017_remove_profile_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other'), ('R', 'rather not say')], max_length=1, null=True),
        ),
    ]
