# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 18:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0018_profile_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='department',
            new_name='uniId',
        ),
        migrations.AddField(
            model_name='profile',
            name='degree_major',
            field=models.CharField(choices=[('MAJOR1', 'MAJOR1'), ('MAJOR2', 'MAJOR2'), ('MAJOR3', 'MAJOR3')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='degree_programme',
            field=models.CharField(choices=[('Science', 'Science'), ('Technology', 'Technology'), ('Engineering', 'Engineering'), ('Mathematics', 'Mathematics')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hear_about',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mentee_number',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='mentor_gender',
            field=models.CharField(choices=[('Definitely', 'Definitely'), ('If possible', 'If possible'), ('Unconcerned', 'Unconcerned')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='study_year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2017)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='why_div_equ_inc',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='why_mentor',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Rather not say', 'Rather not say')], max_length=15, null=True),
        ),
    ]
