# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-23 13:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0020_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='paiMentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webcore.Profile')),
            ],
        ),
    ]
