# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-23 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0021_paimentee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xpairs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Xmentees', to='webcore.Profile')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Xmentors', to='webcore.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='paimentee',
            name='mentor',
        ),
        migrations.DeleteModel(
            name='paiMentee',
        ),
    ]
