# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-23 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0022_auto_20170823_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='paired_with',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webcore.Xpairs'),
        ),
    ]
