# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-23 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0023_profile_paired_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='xpairs',
            name='name',
            field=models.CharField(blank=True, help_text='Enter a unique pair name', max_length=50, null=True),
        ),
    ]
