# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-23 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0024_xpairs_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='paired_with',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
