# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-27 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0025_auto_20170823_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='degree_programme_2',
            field=models.CharField(choices=[('AACOM', 'Advanced Computing (Honours)'), ('AACRD', 'Advanced Computing (R&D) (Honours)'), ('BADAN', 'Applied Data Analytics'), ('HADAN', 'Applied Data Analytics (Honours)'), ('BBIOT', 'Biotechnology'), ('HBIOT', 'Biotechnology (Honours)'), ('AENGI', 'Engineering (Honours)'), ('AENRD', 'Engineering (R&D) (Honours)'), ('BENSU', 'Environment and Sustainability'), ('HENSU', 'Environment and Sustainability (Honours)'), ('AENSU', 'Environment and Sustainability Advanced (Honours)'), ('HENVS', 'Environemntal Studies'), ('BGENE', 'Genetics'), ('HGENE', 'Genetics (Honours)'), ('BHLTH', 'Health Science (Honours)'), ('BIT', 'Information Technology'), ('HIT', 'Information Technology (Honours)'), ('BMASC', 'Mathematical Sciences'), ('HMASC', 'Mathematical Sciences (Honours)'), ('BMEDS', 'Medical Science'), ('HMEDS/HMDSA', 'Medical Science (Honours)'), ('PHBSCIENCE', 'PhB / Bachelor of Philosophy (Honours) in Science'), ('APSYC', 'Psychology (Honours)'), ('BSC', 'Science'), ('HSC', 'Science (Honours)'), ('ASCAD', 'Science (Advanced) (Honours)'), ('BSPSY', 'Science (Psychology)'), ('HSPSY', 'Science (Psychology) (Honours)'), ('ASENG', 'Software Engineering (Honours)'), ('ESCIE', 'Diploma of Science'), ('ECOMP', 'Diploma of Computing')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='degree_programme',
            field=models.CharField(choices=[('AACOM', 'Advanced Computing (Honours)'), ('AACRD', 'Advanced Computing (R&D) (Honours)'), ('BADAN', 'Applied Data Analytics'), ('HADAN', 'Applied Data Analytics (Honours)'), ('BBIOT', 'Biotechnology'), ('HBIOT', 'Biotechnology (Honours)'), ('AENGI', 'Engineering (Honours)'), ('AENRD', 'Engineering (R&D) (Honours)'), ('BENSU', 'Environment and Sustainability'), ('HENSU', 'Environment and Sustainability (Honours)'), ('AENSU', 'Environment and Sustainability Advanced (Honours)'), ('HENVS', 'Environemntal Studies'), ('BGENE', 'Genetics'), ('HGENE', 'Genetics (Honours)'), ('BHLTH', 'Health Science (Honours)'), ('BIT', 'Information Technology'), ('HIT', 'Information Technology (Honours)'), ('BMASC', 'Mathematical Sciences'), ('HMASC', 'Mathematical Sciences (Honours)'), ('BMEDS', 'Medical Science'), ('HMEDS/HMDSA', 'Medical Science (Honours)'), ('PHBSCIENCE', 'PhB / Bachelor of Philosophy (Honours) in Science'), ('APSYC', 'Psychology (Honours)'), ('BSC', 'Science'), ('HSC', 'Science (Honours)'), ('ASCAD', 'Science (Advanced) (Honours)'), ('BSPSY', 'Science (Psychology)'), ('HSPSY', 'Science (Psychology) (Honours)'), ('ASENG', 'Software Engineering (Honours)'), ('ESCIE', 'Diploma of Science'), ('ECOMP', 'Diploma of Computing')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('', '-'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('Rather not say', 'Rather not say')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='study_year',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5+', '5+')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
