# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('mentee_uni_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mentee_name', models.CharField(max_length=50)),
                ('mentee_university', models.CharField(max_length=50)),
                ('mentee_year_study', models.IntegerField()),
                ('mentee_degree', models.CharField(max_length=100)),
                ('mentee_intended_major', models.CharField(max_length=100)),
                ('mentee_gender', models.CharField(max_length=20)),
                ('mentee_gender_of_mentor', models.CharField(choices=[('D', 'Definitely'), ('I', 'If possible'), ('N', 'No preference')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('mentor_uni_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mentor_name', models.CharField(max_length=50)),
                ('mentor_email', models.CharField(max_length=50)),
                ('mentor_university', models.CharField(max_length=100)),
                ('mentor_year_study', models.IntegerField()),
                ('mentor_degree', models.CharField(max_length=100)),
                ('mentor_intended_major', models.CharField(max_length=100)),
                ('mentor_number_mentees', models.IntegerField()),
                ('mentor_gender', models.CharField(max_length=20)),
                ('mentor_gender_of_mentee', models.CharField(choices=[('D', 'Definitely'), ('I', 'If possible'), ('N', 'No preference')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_name', models.CharField(max_length=50)),
                ('mentee_name', models.CharField(max_length=50)),
            ],
        ),
    ]
