# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-27 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pair', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mentee',
            table='mentee',
        ),
        migrations.AlterModelTable(
            name='mentor',
            table='mentor',
        ),
        migrations.AlterModelTable(
            name='pair',
            table='pairs',
        ),
    ]
