# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-27 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pair', '0002_auto_20170627_1130'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pair',
            table='pair',
        ),
    ]
