# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pair', '0003_auto_20170627_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='mentee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pair.Mentee'),
        ),
        migrations.AddField(
            model_name='pair',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pair.Mentor'),
        ),
    ]
