# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 04:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pair', '0005_auto_20170628_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='mentee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pair.Mentee'),
        ),
        migrations.AlterField(
            model_name='pair',
            name='mentor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pair.Mentor'),
        ),
    ]
