# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pair', '0006_auto_20170628_0409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pair',
            name='mentee',
        ),
        migrations.AddField(
            model_name='pair',
            name='mentee',
            field=models.ManyToManyField(to='pair.Mentee'),
        ),
        migrations.RemoveField(
            model_name='pair',
            name='mentor',
        ),
        migrations.AddField(
            model_name='pair',
            name='mentor',
            field=models.ManyToManyField(to='pair.Mentor'),
        ),
    ]
