# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0019_auto_20170430_1835'),
        ('pair', '0007_auto_20170628_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pair',
            name='mentee',
        ),
        migrations.AddField(
            model_name='pair',
            name='mentee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentees', to='webcore.Profile'),
        ),
        migrations.RemoveField(
            model_name='pair',
            name='mentor',
        ),
        migrations.AddField(
            model_name='pair',
            name='mentor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='webcore.Profile'),
        ),
    ]
