# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-03 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pair', '0008_auto_20170628_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pair',
            name='mentee_name',
        ),
        migrations.RemoveField(
            model_name='pair',
            name='mentor_name',
        ),
    ]
