# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pair', '0010_auto_20170704_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='name',
            field=models.CharField(blank=True, help_text='Enter a unique pair name', max_length=50),
        ),
    ]
