# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_document_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Folder',
        ),
    ]
