# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20170708_1404'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Folder',
            new_name='Document',
        ),
    ]
