# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20170709_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='weekly_content',
            field=models.CharField(choices=[('W1', 'Week 1'), ('W2', 'Week 2'), ('W3', 'Week 3'), ('W4', 'Week 4')], default='W1', max_length=2),
        ),
    ]
