# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_document_weekly_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='weekly_content',
            new_name='Folder',
        ),
    ]
