# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20170709_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
