# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_document_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='Folder',
        ),
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
    ]
