# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20170712_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='week',
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
        migrations.DeleteModel(
            name='Week',
        ),
    ]
