# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_auto_20170712_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('semester', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='week',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='myapp.Week'),
            preserve_default=False,
        ),
    ]
