# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20170718_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='week',
        ),
        migrations.AddField(
            model_name='document',
            name='Mentee_Mentor',
            field=models.CharField(choices=[('Week1', 'Week_1'), ('Week2', 'Week_2'), ('Week2', 'Week_3'), ('Week2', 'Week_4')], default='Mentee', max_length=25),
        ),
        migrations.AddField(
            model_name='document',
            name='Name',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='document',
            name='Week',
            field=models.CharField(choices=[('Mentee', 'Mentee'), ('Mentee', 'Mentor'), ('Training', 'Training')], default='Week1', max_length=10),
        ),
        migrations.DeleteModel(
            name='Week',
        ),
    ]
