# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_auto_20170718_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='documents/Week1/Mentee'),
        ),
    ]
