# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_auto_20170718_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='documents/mentee/Mentee'),
        ),
    ]
