# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import myproject.myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20170719_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to=myproject.myapp.models.location),
        ),
    ]
