# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-20 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_auto_20170719_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='Mentee_Mentor',
            field=models.CharField(choices=[('Week1', 'Week_1'), ('Week2', 'Week_2'), ('Week3', 'Week_3'), ('Week4', 'Week_4')], default='Mentee', max_length=25),
        ),
    ]
