# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'other'), ('R', 'rather not say')], max_length=1)),
            ],
        ),
    ]
