# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 13:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0002_user_mentee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_mentee',
            name='user',
            field=models.OneToOneField(default=28, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
