# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0003_auto_20170430_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_mentee',
            name='user',
        ),
        migrations.AddField(
            model_name='user_mentee',
            name='mentor',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
