# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentee', '0005_auto_20170430_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_mentee',
            name='mentor',
        ),
    ]
