# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-13 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20170813_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentee',
            name='docfile',
            field=models.FileField(null=True, upload_to='mentee/'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='docfile',
            field=models.FileField(null=True, upload_to='mentor/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='docfile',
            field=models.FileField(null=True, upload_to='news/'),
        ),
        migrations.AlterField(
            model_name='training',
            name='docfile',
            field=models.FileField(null=True, upload_to='training/'),
        ),
    ]
